### ISSUE TITLE
Broken with multiple authentication methods

### ISSUE THREAD

**Issue by philk** [pivotaltracker/concourse-branch-manager#6]
Attempting to test this out with the examples I get the following error:

Obviously this is due to having both Github and Basic Auth enabled but that seems like a reasonable use case (Github for users, basic auth for bots). `fly login` supports `--username` and `--password` so that seems like a reasonable fix?

```
Downloading fly executable...
Logging into concourse...
1: GitHub
2: Basic Auth
choose an auth method: [redacted-username]
invalid selection (not a number)
[redacted-password]
invalid selection (not a number)
/usr/lib/ruby/gems/2.2.0/gems/process_helper-0.0.3/lib/process_helper.rb:117:in `handle_exit_status': Command failed, pid 17 exit 1. Command: `/tmp/d20160914-7-w1zdsp/fly --target=concourse login --concourse-url=http://concourse-web.build.svc.cluster.local:8080 `. Command Output: "1: GitHub (ProcessHelper::UnexpectedExitStatusError)
2: Basic Auth
choose an auth method: [redacted-username]
invalid selection (not a number)
[redacted-password]
invalid selection (not a number)
"
	from /usr/lib/ruby/gems/2.2.0/gems/process_helper-0.0.3/lib/process_helper.rb:22:in `block in process'
	from /usr/lib/ruby/2.2.0/open3.rb:199:in `popen_run'
	from /usr/lib/ruby/2.2.0/open3.rb:188:in `popen2e'
	from /usr/lib/ruby/gems/2.2.0/gems/process_helper-0.0.3/lib/process_helper.rb:12:in `process'
	from /tmp/build/0e9e5171/concourse-branch-manager/tasks/lib/cbm/pipeline_updater.rb:32:in `set_pipeline'
	from /tmp/build/0e9e5171/concourse-branch-manager/tasks/lib/cbm/branch_manager.rb:49:in `run'
	from concourse-branch-manager/tasks/manage_branches.rb:7:in `<main>'
```

**Comment by thewoolleyman** [comment]
Feel free to submit a PR for this.  It seems like we should support three independent cases, either Github, basic auth, or both?

**Comment by philk** [comment]
Yeah, that makes sense (though I'm not a huge fan of parsing an interactive CLI...).

Sanity check this for me?
```
fly -t blah login

if "choose auth method" prompt:
  match each line like /(\d)\. (\w+)/
  if github and github token:
     select github option
     reply to token prompt
  else basic auth flow:
     select basic auth option
     reply to username and password prompts

else if "username" prompt:
  assume basic auth
  reply to username and password prompts

else if "enter token" prompt:
  reply to token prompt
```

**Comment by thewoolleyman** [comment]
@philk That looks right - but I don't have access to a server configured with github auth, so I can't test any of this out.

**Comment by bbokorney** [comment]
@philk I looked at refactoring it in the way you're describing (using `--username` and `--password`), there isn't a reason you can't do it. However, you need to be careful because if a command fails, it prints the entire command to stderr, which would mean you'd be able to see the username and password in the build log.

**Comment by philk** [comment]
Heh, it's currently doing that anyway (see my [redacted] above) but I agree if we can avoid that it'd be good.

**Comment by thewoolleyman** [comment]
@philk  I would like suppressing the credentials in output to be a separate issue, if it's pre-existing.  Feel free to open one.  If you do, we should be able to do something about it with the proper [process_helper](https://github.com/thewoolleyman/process_helper options) - specifically `:include_output_in_exception` and/or `:puts_output`
