### ISSUE TITLE
Discovering multiple matching branches at one time breaks generation task

### ISSUE THREAD

**Issue by crstamps2** [pivotaltracker/concourse-branch-manager#9]
If there are multiple branches that it deems ready to spin up new pipelines for, the job breaks as it is not properly generating the yaml. Here is an example output from the branch-manager job:

```
jobs:
- name: Unit Test (feature-concourse-pipeline-generator)
  plan:
  - get: Contracts(feature-concourse-pipeline-generator) #TODO: change to your source repo
    resource: Contracts(feature-concourse-pipeline-generator)
    trigger: true
    params: {depth: 20}
  - task: Test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: docker.artifactory.homedepot.com/flow/rubymysql, tag: latest }
      inputs:
        - name: Contracts(feature-concourse-pipeline-generator)
      run:
        dir: Contracts(feature-concourse-pipeline-generator)
        path: ./ci/build-branch.sh
      params:
        TARGET_ENV: acceptance
        ENVIRONMENT: acceptance
        CF_API_ENDPOINT: api.run-np.homedepot.com
        GITHUB_PRIVATE_KEY: {{github-private-key}}
        GITHUB_TOKEN: {{github-token}}
        DEPLOYMENT_USER: {{deployment-user}}
---> DEPLOYMENT_PWD: {{deployment-pwd}}- name: Unit Test (feature-test-pipeline-generator) <---
  plan:
  - get: Contracts(feature-test-pipeline-generator) #TODO: change to your source repo
    resource: Contracts(feature-test-pipeline-generator)
    trigger: true
    params: {depth: 20}
  - task: Test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: docker.artifactory.homedepot.com/flow/rubymysql, tag: latest }
      inputs:
        - name: Contracts(feature-test-pipeline-generator)
      run:
        dir: Contracts(feature-test-pipeline-generator)
        path: ./ci/build-branch.sh
      params:
        TARGET_ENV: acceptance
        ENVIRONMENT: acceptance
        CF_API_ENDPOINT: api.run-np.homedepot.com
        GITHUB_PRIVATE_KEY: {{github-private-key}}
        GITHUB_TOKEN: {{github-token}}
        DEPLOYMENT_USER: {{deployment-user}}
        DEPLOYMENT_PWD: {{deployment-pwd}}
resource_types:

```

As you can see in the highlighted line, the next job was printed on the same line as the previous param. This is causing the following error:

```bash
target saved
Updating pipeline...
failed to unmarshal configStructure: yaml: line 19: mapping values are not allowed in this context
/usr/lib/ruby/gems/2.2.0/gems/process_helper-0.0.3/lib/process_helper.rb:117:in `handle_exit_status': Command failed, pid 28 exit 1. Command: `/tmp/d20170324-7-8eboiv/fly --target=concourse set-pipeline --config=/tmp/d20170324-7-1xlmyt4/pipeline.yml --pipeline=cbm-contracts --load-vars-from=credentials-repo/secrets.yml`. Command Output: "failed to unmarshal configStructure: yaml: line 19: mapping values are not allowed in this context (ProcessHelper::UnexpectedExitStatusError)
"
	from /usr/lib/ruby/gems/2.2.0/gems/process_helper-0.0.3/lib/process_helper.rb:22:in `block in process'
	from /usr/lib/ruby/2.2.0/open3.rb:199:in `popen_run'
	from /usr/lib/ruby/2.2.0/open3.rb:188:in `popen2e'
	from /usr/lib/ruby/gems/2.2.0/gems/process_helper-0.0.3/lib/process_helper.rb:12:in `process'
	from /tmp/build/0e9e5171/concourse-branch-manager/tasks/lib/cbm/pipeline_updater.rb:38:in `set_pipeline'
	from /tmp/build/0e9e5171/concourse-branch-manager/tasks/lib/cbm/branch_manager.rb:49:in `run'
	from concourse-branch-manager/tasks/manage_branches.rb:7:in `<main>'

```

**Comment by crstamps2** [comment]
I just tried adding more new lines at the bottom of my template yml and it is now on a different line, however I still get the same error.

**Comment by crstamps2** [comment]
It is also happening in the resource template as well. Adding the new line to my resource template fixed the problem completely. I think the solution is more resiliency to add a new line before writing out the next resource or job.

**Comment by thewoolleyman** [comment]
Hi @crstamps2,

Thanks for the feedback.

However, we aren't using concourse branch manager anymore and won't be maintaining it.

I'd be happy to turn it over to someone who would like to maintain it, or, in the meantime, to accept (but not validate or test) any PRs.

**Comment by crstamps2** [comment]
bummer. Are you using an alternative? I may be willing to take this over.

**Comment by thewoolleyman** [comment]
We are moving to a different tool.  If you are interested in taking over,
you can email me directly and we can discuss it further.
